CREATE DATABASE IF NOT EXISTS `DATABASE`;
USE `DATABASE`;
CREATE TABLE IF NOT EXISTS `USERS` (
  `NAME` varchar(255) NOT NULL,
  `TOKEN` varchar(255) NOT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `USERS` VALUES ('admin', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOQU1FIjoiYWRtaW4iLCJQSU4iOiIxMjM0IiwiaWF0IjoxNjg3NDMzNDE2fQ.m9fF4KxmhMg3jsRHthxAimCowU_A_2uzeuP6--CZRDg');